spring:
  application:
    name: mysprinfboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.158.129:3306/mysql
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: -8
        min-idle: 0
    timeout: 1000
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  file:
    path: /Users/jackie/workspace/rome/
    name: springbootdemo.log

